services:
  onair:
    build: .
    container_name: onair-regie
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      # Montage du dossier entier pour que le serveur puisse Ã©crire onair.json
      - ./public:/app/public
